baseURL = 'https://ArtByElla.de/'
languageCode = 'de-de'
title = 'Art By Ella'
copyright = 'Sophia Élaine Stein'

theme = "blogge-hugo-themee"

[menu]
  [[menu.main]]
    name = "Home"
    url = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Categorys"
    url = ""
    weight = "2"
  [[menu.main]]
    identifier = "words"
    name = "Words"
    url = "tags/words"
    parent = "tags"
    weight = 1
  [[menu.main]]
    identifier = "drawing"
    name = "Drawing"
    url = "tags/drawing"
    parent = "tags"
    weight = 2
  [[menu.main]]
    name = "About Me"
    url = "about"
    weight = 3

[params]
  summarylength = 80
  logo = "images/artbyella.svg"
  author = "Sophia Élaine Stein"
  contactmailaddress = "sophia@artbyella.de"
  authorThumb= "images/ella.png"
  instaUsernameLya = "_lya_o.0"
  instaUsername = "el.draw03"
  trendingBlogIcon = "images/icon.svg"
  pinterestUsername = "5f5f4315d345e282be278e71bc948a"
  deviantartUsername = "elaine003"
  blogTitle = "Beiträge"
  blogSubTitle = "Zeige die neusten Beiträge"

[taxonomies]
  tag = "tags"